services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty@postgres:5432/dockerDB
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=dockerDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
